matlang2c: assignment.c expr.c f4.c main.c matrix.c print.c printsep.c scalar.c searcher.c split.c stacksolver.c vector.c
	gcc -o matlang2c assignment.c expr.c f4.c main.c matrix.c print.c printsep.c scalar.c searcher.c split.c stacksolver.c vector.c -I . 
